version: '3.8'
services:
  postgre_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: userApi
      POSTGRES_PASSWORD: api
      POSTGRES_DB: api-movies
    ports:
      - "5433:5432"
  
    restart: always
